repos:
  - repo: https://github.com/python/black
    rev: 19.10b0
    hooks:
      - id: black
        language_version: python3.6
        exclude: ^template/
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.9
    hooks:
      - id: flake8
        exclude: ^template/
        additional_dependencies: [ 'pydocstyle==3.0.0', 'flake8-docstrings', 'flake8-rst-docstrings']
